### PR TITLE
Undo functionality bug fix

### LINKED ISSUE #91: Undoing after changing vendor restores back the previous order (despite having different menu)

### PR DESCRIPTION
**Pull request by KendrewChan**

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/VendorCommand.java [hunk 1]
```diff
@@ -47,6 +47,8 @@ public CommandResult execute(Model model) throws CommandException {
         model.setVendorIndex(index);
 
         if (oldIndex != index) {
+            model.clearOrderHistory();
+            // Note that clearOrder also saved the new Order into current OrderHistory
             model.clearOrder();
```
Comment (weixin-tan) [inline src/main/java/seedu/address/logic/commands/VendorCommand.java]: Might want to wrap this logic into a Model#resetOrder() instead.

File: src/main/java/seedu/address/model/order/OrderManager.java [hunk 2]
```diff
@@ -63,6 +63,13 @@ public void setOrder(List<OrderItem> orderItems) {
         saveChanges();
     }
 
+    /**
+     * Clears the contents of orderHistory.
+     */
+    public void clearOrderHistory() {
+        this.orderHistory.clear();
+    }
```
Comment (weixin-tan) [inline src/main/java/seedu/address/model/order/OrderManager.java]: If called by itself, the assumption that the head of orderHistory is equal to order is no longer true.

**Review by weixin-tan — CHANGES_REQUESTED** [review]

**Review by weixin-tan — APPROVED** [review]
lgtm
